name 'openidm'
maintainer 'Matt Mencel'
maintainer_email 'mr-mencel@wiu.edu'
license 'Apache 2.0'
description 'Installs/Configures openidm'
long_description 'Installs/Configures openidm'
version '0.3.6'

supports 'centos'

depends 'ark', '~> 0.9.0'
depends 'database', '~> 4.0.0'
depends 'java', '~> 1.36.0'
depends 'mysql', '~> 6.0.0'
depends 'mysql2_chef_gem', '~> 1.0.0'
depends 'mysql_connector', '~> 0.8.0'
